### ISSUE TITLE
npm run run fails to start script on Ubuntu

### ISSUE THREAD

**Issue by noahc66260** [thepont/graphql-aggregate-sample#1]
I'm trying to run this project and I am getting errors I don't understand. I am running this with the latest libraries available, so this should be pretty straightforward to replicate.

$ npm run run

> graphql-aggregate-sample@1.0.0 run /home/noah/Documents/blockview/graphql/graphql-aggregate-sample
> babel-node index

/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: PersonNoIntSum fields must be an object with field names as keys or a function which returns such an object.
    at invariant (/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/jsutils/invariant.js:19:11)
    at defineFieldMap (/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/definition.js:269:27)
    at GraphQLObjectType.getFields (/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/definition.js:235:44)
    at /home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:219:7)
    at /home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:217:22
    at Array.forEach (<anonymous>)
    at /home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:208:29
    at typeMapReducer (/home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:219:7)
    at /home/noah/Documents/blockview/graphql/graphql-aggregate-sample/node_modules/graphql/type/schema.js:217:22
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-aggregate-sample@1.0.0 run: `babel-node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-aggregate-sample@1.0.0 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thepont** [comment]
Hey, seems graphql-aggregate is broken. :/ I'll see if I can take a look at some stage.
